[package]
name = "scmp"
version = "0.1.2"
authors = ["Gabriel de Perthuis <g2p.code@gmail.com>"]
build = "build.rs"
keywords = ["linux", "seccomp"]
license = "ISC"
description = "Bindings to libseccomp"
repository = "https://github.com/g2p/scmp"

[build-dependencies]
bindgen = ">= 0.69.4"

